@startuml design

package bonsaidiary {

	interface cli <<cli interface>> {
		main()
		getEntry()
		config()
	}

	interface diary <<saves images and metadata>> {
		save(data)
	}

	class insta <<posts to instagram>> {
		__init__(username, password)
		post(data)
	}

	interface crop <<crops images for posting>> {
		crop(ImageBuffer): ImageBuffer
	}

	cli -d- diary
	cli-d- insta
	cli -d- crop

}

@enduml

